# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: circleci/python:3.8
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run: |
          cd cool_counters
          python3 -m pip
          pip install django
          python3 manage.py migrate
          python manage.py runserver

          echo "Gurkirpa@12345" | docker login --username gurprit123 --password-stdin
          docker run -d --name circlci circleci/python:3.8

        # build the application image
      - run: docker build -t circleci/python:3.8 .

     # deploy the image
      - run: docker push circleci/python:3.8    



# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
